<script setup>
import { ref } from "vue";
import { RouterLink, RouterView } from "vue-router";

const showMenu = ref(false)
</script>

<template>
  <div class="bg-white bg-opacity-40">
    <header
      class="w-full px-6 py-2 bg-white z-40 sticky top-0 flex justify-between items-center border-b border-lightGrey"
      :class="showMenu ? 'bg-opacity-70' : ''">
      <button :class="showMenu ? 'container change w-max' : 'container w-max'" @click="showMenu = !showMenu">
        <div class="bar1"></div>
        <div class="bar2"></div>
        <div class="bar3"></div>
      </button>
    </header>
    <div v-if="showMenu" class="py-4 px-10 w-full lg:w-1/5 z-30 bg-white h-full slide-in-left fixed">
      <div class="sticky top-0 h-full flex flex-col text-center gap-y-6">
        <RouterLink to="/" class="border-b py-1"> Home </RouterLink>
        <RouterLink to="/about">About</RouterLink>
      </div>
    </div>
  </div>

  <RouterView />
</template>

<style scoped>
.bg-nature {
  background: none;
}

@media only screen and (min-width: 1280px) {
  .bg-nature {
    background-image: url('@/static/img/bg-forest.jpg');
    background-size: 100% auto;
    background-attachment: fixed;
    background-repeat: no-repeat;
  }
}

.nuxt-link-exact-active {
  font-weight: 600;
  text-decoration: underline;
}

.container {
  display: inline-block;
  cursor: pointer;
}

.bar1,
.bar2,
.bar3 {
  width: 35px;
  height: 5px;
  background-color: #333;
  margin: 6px 0;
  transition: 0.4s;
}

.change .bar1 {
  -webkit-transform: rotate(-45deg) translate(-9px, 6px);
  transform: rotate(-45deg) translate(-9px, 6px);
}

.change .bar2 {
  opacity: 0;
}

.change .bar3 {
  -webkit-transform: rotate(45deg) translate(-8px, -8px);
  transform: rotate(45deg) translate(-8px, -8px);
}

.slide-in-left {
  -webkit-animation: slide-in-left 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94) forwards;
  animation: slide-in-left 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94) forwards;
}

/* ----------------------------------------------
 * Generated by Animista on 2021-8-15 19:56:0
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */
@-webkit-keyframes slide-in-left {
  0% {
    -webkit-transform: translateX(-1000px);
    transform: translateX(-1000px);
    opacity: 0;
  }

  100% {
    -webkit-transform: translateX(0);
    transform: translateX(0);
    opacity: 1;
  }
}

@keyframes slide-in-left {
  0% {
    -webkit-transform: translateX(-1000px);
    transform: translateX(-1000px);
    opacity: 0;
  }

  100% {
    -webkit-transform: translateX(0);
    transform: translateX(0);
    opacity: 1;
  }
}
</style>